'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, MapPin, Minus, Plus, ShoppingBag, Star, Music2, X } from 'lucide-react'

const categories = ['Все', 'Овощи', 'Грибы', 'Морепродукты', 'Острые']
const products = [
  { id: 1, category: 'Овощи', name: 'Морковь по-корейски', description: 'Хрустящая морковь, чеснок, кориандр и горячее масло.', price: 85, unit: '100 г', image: '/images/korean-carrot.png', tag: 'Хит' },
  { id: 2, category: 'Овощи', name: 'Баклажаны по-корейски', description: 'Синие с перцем, зеленью и пряным маринадом.', price: 95, unit: '100 г', image: '/images/eggplant.png', tag: 'Советуем' },
  { id: 3, category: 'Острые', name: 'Кимчи / кимча', description: 'Пекинская капуста, красный перец, чеснок и соевый соус.', price: 110, unit: '100 г', image: '/images/kimchi.png', tag: 'Остро' },
  { id: 4, category: 'Овощи', name: 'Цветная капуста', description: 'Хрустящие соцветия в пряно-кислом маринаде.', price: 80, unit: '100 г', image: '/images/korean-pickles-hero.png', tag: 'Свежая партия' },
  { id: 5, category: 'Грибы', name: 'Шампиньоны по-корейски', description: 'Целые грибы с луком, зеленью и ароматным маслом.', price: 105, unit: '100 г', image: '/images/eggplant.png', tag: 'Нежные' },
  { id: 6, category: 'Морепродукты', name: 'Кальмары по-корейски', description: 'Нежная соломка кальмара в пряном перечном маринаде.', price: 175, unit: '100 г', image: '/images/kimchi.png', tag: 'Морепродукты' },
  { id: 7, category: 'Овощи', name: 'Пелюстка со свёклой', description: 'Капуста, свёкла и чеснок — ярко, сочно и хрустяще.', price: 75, unit: '100 г', image: '/images/korean-pickles-hero.png', tag: 'Классика' },
  { id: 8, category: 'Острые', name: 'Огурцы по-корейски', description: 'Свежие огурцы, кунжут и перечное масло.', price: 90, unit: '100 г', image: '/images/korean-carrot.png', tag: 'Хруст' },
]

export function KFoodSite() {
  const [active, setActive] = useState('Все')
  const [cart, setCart] = useState<Record<number, number>>({})
  const [cartOpen, setCartOpen] = useState(false)
  const filtered = active === 'Все' ? products : products.filter((p) => p.category === active)
  const totalItems = Object.values(cart).reduce((s, n) => s + n, 0)
  const total = useMemo(() => products.reduce((s, p) => s + p.price * (cart[p.id] ?? 0), 0), [cart])
  const add = (id: number) => setCart((c) => ({ ...c, [id]: (c[id] ?? 0) + 1 }))
  const remove = (id: number) => setCart((c) => ({ ...c, [id]: Math.max(0, (c[id] ?? 0) - 1) }))

  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/60 bg-background/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><a href="#top" className="font-sans text-2xl font-black tracking-[-0.08em]">У <span className="text-primary">Виктории</span></a><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#menu">Соленья</a><a href="#markets">Где купить</a><a href="#about">О нас</a></nav><button onClick={() => setCartOpen(true)} className="flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground" aria-label="Открыть корзину"><ShoppingBag size={16} /> Заказ {totalItems > 0 && `(${totalItems})`}</button></div></header>
    <main id="top">
      <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-12 lg:grid-cols-[0.95fr_1.05fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-20"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 font-mono text-xs font-bold uppercase tracking-wider"><span className="h-2 w-2 rounded-full bg-accent" /> Одесса · 2026</div><h1 className="max-w-xl font-sans text-5xl font-black leading-[0.94] tracking-[-0.06em] text-balance sm:text-7xl">Домашние<br /><span className="text-primary">соленья</span><br />с характером.</h1><p className="mt-7 max-w-md text-base leading-7 text-muted-foreground">Корейские салаты, кимчи и свежие морепродукты по-домашнему. Для своих — с любовью и щедрой ложкой.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#menu" className="inline-flex items-center gap-3 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground">Выбрать соленья <ArrowRight size={17} /></a><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-border px-6 py-3.5 text-sm font-bold">Смотреть TikTok</a></div><div className="mt-9 flex items-center gap-3 text-sm"><div className="flex gap-1 text-primary"><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /><Star size={14} fill="currentColor" /></div><span className="text-muted-foreground">11K подписчиков у @u_vicktorii</span></div></div><div className="relative"><div className="aspect-[1.05] overflow-hidden rounded-[2rem] bg-secondary"><img src="/images/korean-pickles-hero.png" alt="Ассорти домашних корейских солений" className="h-full w-full object-cover" /></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-card p-4 shadow-xl sm:-left-6"><p className="font-mono text-xs font-bold uppercase text-muted-foreground">Сегодня на витрине</p><p className="mt-1 text-lg font-black">свежая партия</p></div><div className="absolute -right-2 top-6 rounded-full bg-accent px-4 py-3 font-mono text-xs font-black uppercase tracking-wider sm:-right-5">остренько</div></div></section>
      <section className="border-y border-border bg-primary py-5 text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-2 px-5 font-mono text-xs font-bold uppercase tracking-widest sm:justify-between lg:px-10"><span>Весовые соленья</span><span className="hidden sm:inline">✦</span><span>Соберём ассорти</span><span className="hidden sm:inline">✦</span><span>Доставка по Одессе</span><span className="hidden sm:inline">✦</span><span>Спросите Викторию</span></div></section>
      <section id="menu" className="mx-auto max-w-7xl px-5 py-20 lg:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">Витрина</p><h2 className="mt-3 font-sans text-4xl font-black tracking-[-0.05em] sm:text-5xl">Набирай<br />сколько хочется.</h2><p className="mt-3 text-sm text-muted-foreground">Цены указаны за 100 г · можно собрать свой микс</p></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((c) => <button key={c} onClick={() => setActive(c)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold ${active === c ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-secondary'}`}>{c}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((p) => <article key={p.id} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="relative aspect-square overflow-hidden bg-secondary"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-card px-3 py-1 font-mono text-[10px] font-bold uppercase">{p.tag}</span></div><div className="p-4"><div className="flex items-start justify-between gap-2"><h3 className="text-base font-black leading-tight">{p.name}</h3><span className="whitespace-nowrap font-mono text-sm font-bold">{p.price} ₴</span></div><p className="mt-2 text-sm leading-5 text-muted-foreground">{p.description}</p><button onClick={() => add(p.id)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-secondary py-3 text-sm font-bold hover:bg-primary hover:text-primary-foreground"><Plus size={16} /> Добавить</button></div></article>)}</div></section>
      <section id="markets" className="bg-secondary px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">Забирайте лично</p><div className="mt-4 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-7"><MapPin className="text-primary" /><h3 className="mt-8 text-2xl font-black">Черёмушки</h3><p className="mt-2 leading-6 text-muted-foreground">Одесса, рынок на Черёмушках<br />Свежие салаты и морепродукты</p></div><div className="rounded-2xl border border-border bg-card p-7"><MapPin className="text-primary" /><h3 className="mt-8 text-2xl font-black">Новый рынок</h3><p className="mt-2 leading-6 text-muted-foreground">Одесса, Новый рынок<br />Заходите за баночкой к обеду</p></div></div></div></section>
      <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-2 lg:px-10"><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground sm:p-12"><Music2 size={30} /><p className="mt-12 max-w-lg text-3xl font-black leading-tight tracking-[-0.04em]">«Домашние маринады и свежие морепродукты — каждый день для Одессы».</p><div className="mt-8 font-mono text-xs font-bold uppercase tracking-widest">@u_vicktorii · 170.3K лайков</div></div><div className="flex flex-col justify-center rounded-[2rem] border border-border p-8 sm:p-12"><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">На связи</p><h2 className="mt-4 text-3xl font-black tracking-[-0.04em]">Есть вопрос по<br />ассорти или доставке?</h2><p className="mt-4 leading-7 text-muted-foreground">Напишите Виктории в Viber или TikTok — подскажем, что сегодня самое свежее.</p><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" className="mt-7 inline-flex w-fit items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-bold">Открыть TikTok <ArrowRight size={16} /></a></div></section>
    </main>
    <footer className="border-t border-border px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm sm:flex-row sm:items-center sm:justify-between"><div className="font-sans text-xl font-black tracking-[-0.08em]">У <span className="text-primary">Виктории</span></div><div className="flex items-center gap-5 text-muted-foreground"><span className="inline-flex items-center gap-2"><MapPin size={15} /> Одесса</span><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" aria-label="TikTok"><Music2 size={17} /></a></div><span className="text-muted-foreground">© 2026 У Виктории</span></div></footer>
    {totalItems > 0 && <button onClick={() => setCartOpen(true)} className="fixed bottom-5 right-5 z-30 flex items-center gap-3 rounded-full bg-primary px-5 py-4 text-sm font-bold text-primary-foreground shadow-2xl"><ShoppingBag size={18} /> В заказе {totalItems} · {total} ₴</button>}
    {cartOpen && <div className="fixed inset-0 z-50 flex items-end justify-end bg-foreground/40 sm:items-stretch"><button className="absolute inset-0 cursor-default" onClick={() => setCartOpen(false)} aria-label="Закрыть заказ" /><aside className="relative flex h-[80vh] w-full flex-col rounded-t-3xl bg-card p-6 sm:h-full sm:max-w-md sm:rounded-none"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Ваш заказ</h2><button onClick={() => setCartOpen(false)} aria-label="Закрыть"><X /></button></div><div className="flex-1 overflow-y-auto py-6">{products.filter((p) => cart[p.id]).map((p) => <div key={p.id} className="flex items-center justify-between gap-3 border-b border-border py-4"><div><p className="font-bold">{p.name}</p><p className="font-mono text-sm text-muted-foreground">{p.price} ₴ / {p.unit}</p></div><div className="flex items-center gap-3"><button onClick={() => remove(p.id)} className="rounded-full border p-1" aria-label={`Уменьшить ${p.name}`}><Minus size={14} /></button><span className="font-mono text-sm">{cart[p.id]}</span><button onClick={() => add(p.id)} className="rounded-full border p-1" aria-label={`Увеличить ${p.name}`}><Plus size={14} /></button></div></div>)}</div><div className="border-t border-border pt-5"><div className="flex justify-between text-lg font-black"><span>Итого</span><span>{total} ₴</span></div><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-4 font-bold text-primary-foreground"><Check size={18} /> Уточнить заказ в TikTok</a></div></aside></div>}
  </div>
}

export default KFoodSite
