'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, Camera, MapPin, Minus, Plus, ShoppingBag, Star, Music2, X } from 'lucide-react'

const categories = ['Все', 'Топ', 'Корн-доги', 'Ттокпокки', 'Напитки']

const menu = [
  { id: 1, category: 'Топ', name: 'Корн-дог с моцареллой', description: 'Тянущаяся моцарелла, хрустящая корочка и соус на выбор', price: 390, image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=900&q=85', tag: 'Хит' },
  { id: 2, category: 'Топ', name: 'Корн-дог с сосиской', description: 'Классика корейского стритфуда с сахарной корочкой', price: 350, image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=85', tag: 'Любимый' },
  { id: 3, category: 'Ттокпокки', name: 'Ттокпокки', description: 'Рисовые клёцки в густом остром соусе с кунжутом', price: 490, image: 'https://images.unsplash.com/photo-1635363638580-c2809d049eee?auto=format&fit=crop&w=900&q=85', tag: 'Остро' },
  { id: 4, category: 'Корн-доги', name: 'Корн-дог картофельный', description: 'Хрустящий картофель снаружи, сыр внутри', price: 430, image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=900&q=85', tag: 'Новинка' },
  { id: 5, category: 'Напитки', name: 'Корейский лимонад', description: 'Свежий цитрус, лёд и немного сладости', price: 250, image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85', tag: 'Освежает' },
  { id: 6, category: 'Топ', name: 'Сет «Попробуй всё»', description: 'Два корн-дога, ттокпокки и два лимонада', price: 1190, image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0d4?auto=format&fit=crop&w=900&q=85', tag: 'Выгодно' },
]

export function KFoodSite() {
  const [active, setActive] = useState('Все')
  const [cart, setCart] = useState<Record<number, number>>({})
  const [cartOpen, setCartOpen] = useState(false)
  const filtered = active === 'Все' ? menu : menu.filter((item) => item.category === active)
  const totalItems = Object.values(cart).reduce((sum, quantity) => sum + quantity, 0)
  const total = useMemo(() => menu.reduce((sum, item) => sum + item.price * (cart[item.id] ?? 0), 0), [cart])
  const add = (id: number) => setCart((current) => ({ ...current, [id]: (current[id] ?? 0) + 1 }))
  const remove = (id: number) => setCart((current) => ({ ...current, [id]: Math.max((current[id] ?? 0) - 1, 0) }))

  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/60 bg-background/90 backdrop-blur-md">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10">
        <a href="#top" className="font-mono text-lg font-black tracking-[-0.08em]">KOR<span className="text-primary">E</span>A</a>
        <nav className="hidden items-center gap-8 text-sm font-semibold md:flex"><a href="#menu" className="transition-opacity hover:opacity-60">Меню</a><a href="#how" className="transition-opacity hover:opacity-60">Как заказать</a><a href="#about" className="transition-opacity hover:opacity-60">О нас</a></nav>
        <button onClick={() => setCartOpen(true)} className="flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm font-bold text-primary-foreground transition-transform hover:scale-105" aria-label="Открыть корзину"><ShoppingBag size={16} /> Корзина {totalItems > 0 && <span>({totalItems})</span>}</button>
      </div>
    </header>

    <main id="top">
      <section className="mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-14 lg:grid-cols-[1.02fr_0.98fr] lg:items-center lg:px-10 lg:pb-28 lg:pt-20">
        <div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-2 font-mono text-xs font-bold uppercase tracking-wider"><span className="h-2 w-2 rounded-full bg-accent" /> Корейский стритфуд · Москва</div><h1 className="max-w-xl font-sans text-5xl font-black leading-[0.95] tracking-[-0.06em] text-balance sm:text-7xl">Корейская<br /><span className="text-primary">вкуснота</span><br />рядом.</h1><p className="mt-7 max-w-md text-base leading-7 text-muted-foreground">Корн-доги, ттокпокки и настроение Сеула. Заказывай на дом или заглядывай за горячим прямо сейчас.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#menu" className="inline-flex items-center gap-3 rounded-full bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground transition-transform hover:scale-105">Выбрать вкус <ArrowRight size={17} /></a><a href="#how" className="inline-flex items-center gap-2 rounded-full border border-border px-6 py-3.5 text-sm font-bold transition-colors hover:bg-secondary">Как это работает</a></div><div className="mt-10 flex items-center gap-5 text-sm"><div className="flex -space-x-2"><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-background bg-secondary text-xs">Е</span><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-background bg-primary text-xs text-primary-foreground">А</span><span className="flex h-9 w-9 items-center justify-center rounded-full border-2 border-background bg-accent text-xs">К</span></div><div><div className="flex gap-1"><Star size={13} fill="currentColor" /> <Star size={13} fill="currentColor" /> <Star size={13} fill="currentColor" /> <Star size={13} fill="currentColor" /> <Star size={13} fill="currentColor" /></div><span className="text-muted-foreground">любят нас в TikTok</span></div></div></div>
        <div className="relative"><div className="aspect-[0.95] overflow-hidden rounded-[2rem] bg-secondary"><img src="https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=90" alt="Корейский корн-дог с расплавленным сыром" className="h-full w-full object-cover" /></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-card p-4 shadow-xl sm:-left-6"><p className="font-mono text-xs font-bold uppercase text-muted-foreground">Сегодня готовим</p><p className="mt-1 text-lg font-black">с 12:00 до 22:00</p></div><div className="absolute -right-2 top-6 rounded-full bg-accent px-4 py-3 font-mono text-xs font-black uppercase tracking-wider sm:-right-5">hot & crispy</div></div>
      </section>

      <section className="border-y border-border bg-primary py-5 text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-2 px-5 font-mono text-xs font-bold uppercase tracking-widest sm:justify-between lg:px-10"><span>Доставка от 60 минут</span><span className="hidden sm:inline">✦</span><span>Свежая начинка</span><span className="hidden sm:inline">✦</span><span>Соусы в подарок</span><span className="hidden sm:inline">✦</span><span>Без скучной еды</span></div></section>

      <section id="menu" className="mx-auto max-w-7xl px-5 py-20 lg:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">Меню</p><h2 className="mt-3 font-sans text-4xl font-black tracking-[-0.05em] sm:text-5xl">Выбирай свой<br />корейский вайб.</h2></div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((category) => <button key={category} onClick={() => setActive(category)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold transition-colors ${active === category ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-secondary'}`}>{category}</button>)}</div></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((item) => <article key={item.id} className="group overflow-hidden rounded-2xl border border-border bg-card transition-shadow hover:shadow-xl"><div className="relative aspect-[1.12] overflow-hidden bg-secondary"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105" /><span className="absolute left-3 top-3 rounded-full bg-card px-3 py-1 font-mono text-[10px] font-bold uppercase">{item.tag}</span></div><div className="p-5"><div className="flex items-start justify-between gap-4"><h3 className="text-lg font-black">{item.name}</h3><span className="whitespace-nowrap font-mono text-sm font-bold">{item.price} ₽</span></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.description}</p><button onClick={() => add(item.id)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-secondary py-3 text-sm font-bold transition-colors hover:bg-primary hover:text-primary-foreground"><Plus size={16} /> Добавить</button></div></article>)}</div></section>

      <section id="how" className="bg-secondary px-5 py-20 lg:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">Доставка</p><h2 className="mt-3 max-w-md text-4xl font-black tracking-[-0.05em] sm:text-5xl">Горячее —<br />прямо к двери.</h2><p className="mt-5 max-w-sm leading-7 text-muted-foreground">Соберём заказ, пока ты выбираешь любимый плейлист. Никаких сложностей — только вкусная часть дня.</p></div><div className="grid gap-8 sm:grid-cols-3">{[['01','Выбери','Добавь любимые блюда в корзину.'],['02','Закажи','Оформи доставку в пару кликов.'],['03','Наслаждайся','Мы привезём всё горячим и хрустящим.']].map(([num,title,text]) => <div key={num} className="border-t-2 border-primary pt-4"><span className="font-mono text-xs font-bold text-primary">{num}</span><h3 className="mt-8 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></div></section>

      <section id="about" className="mx-auto grid max-w-7xl gap-8 px-5 py-20 lg:grid-cols-2 lg:px-10"><div className="rounded-[2rem] bg-primary p-8 text-primary-foreground sm:p-12"><Music2 size={30} /><p className="mt-12 max-w-lg text-3xl font-black leading-tight tracking-[-0.04em]">«Сняли первое видео — и поняли, что хотим делиться этим вкусом каждый день».</p><div className="mt-8 flex items-center gap-3 font-mono text-xs font-bold uppercase tracking-widest"><span className="h-8 w-8 rounded-full bg-primary-foreground/20" /> @u_vicktorii</div></div><div className="flex flex-col justify-center rounded-[2rem] border border-border p-8 sm:p-12"><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">Мы на связи</p><h2 className="mt-4 text-3xl font-black tracking-[-0.04em]">Есть вопросы?<br />Пиши нам.</h2><p className="mt-4 leading-7 text-muted-foreground">Следи за новинками, закулисьем и свежими дропами в TikTok.</p><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" className="mt-7 inline-flex w-fit items-center gap-2 rounded-full border border-border px-5 py-3 text-sm font-bold hover:bg-secondary">Открыть TikTok <ArrowRight size={16} /></a></div></section>
    </main>

    <footer className="border-t border-border px-5 py-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 text-sm sm:flex-row sm:items-center sm:justify-between"><div className="font-mono font-black tracking-[-0.08em]">KOR<span className="text-primary">E</span>A</div><div className="flex items-center gap-5 text-muted-foreground"><span className="inline-flex items-center gap-2"><MapPin size={15} /> Москва</span><a href="https://www.tiktok.com/@u_vicktorii" target="_blank" rel="noreferrer" aria-label="TikTok"><Music2 size={17} /></a><Camera size={17} /></div><span className="text-muted-foreground">© 2024 Korea Street Food</span></div></footer>

    {totalItems > 0 && <button onClick={() => setCartOpen(true)} className="fixed bottom-5 right-5 z-30 flex items-center gap-3 rounded-full bg-primary px-5 py-4 text-sm font-bold text-primary-foreground shadow-2xl"><ShoppingBag size={18} /> В корзине {totalItems} · {total} ₽</button>}
    {cartOpen && <div className="fixed inset-0 z-50 flex items-end justify-end bg-foreground/40 sm:items-stretch"><button className="absolute inset-0 cursor-default" onClick={() => setCartOpen(false)} aria-label="Закрыть корзину" /><aside className="relative flex h-[80vh] w-full flex-col rounded-t-3xl bg-card p-6 sm:h-full sm:max-w-md sm:rounded-none"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">Твоя корзина</h2><button onClick={() => setCartOpen(false)} aria-label="Закрыть"><X /></button></div><div className="flex-1 overflow-y-auto py-6">{menu.filter((item) => cart[item.id]).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-border py-4"><div><p className="font-bold">{item.name}</p><p className="font-mono text-sm text-muted-foreground">{item.price} ₽</p></div><div className="flex items-center gap-3"><button onClick={() => remove(item.id)} className="rounded-full border p-1" aria-label={`Уменьшить ${item.name}`}><Minus size={14} /></button><span className="font-mono text-sm">{cart[item.id]}</span><button onClick={() => add(item.id)} className="rounded-full border p-1" aria-label={`Увеличить ${item.name}`}><Plus size={14} /></button></div></div>)}{totalItems === 0 && <p className="py-10 text-center text-muted-foreground">Корзина пока пустая.</p>}</div><div className="border-t border-border pt-5"><div className="flex justify-between text-lg font-black"><span>Итого</span><span>{total} ₽</span></div><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-4 font-bold text-primary-foreground"><Check size={18} /> Перейти к оформлению</button></div></aside></div>}
  </div>
}

export default KFoodSite
